function toolboxQuestion(i){
 const qs=[
  ()=>numeric("A toolbox has 2 rows of 4 nails. How many nails?",8,"2 groups of 4."),
  ()=>numeric("3 boards need 5 screws each. How many screws?",15,"3 groups of 5."),
  ()=>numeric("A board is 4 cm by 3 cm. What is its area?",12,"Length × width."),
  ()=>mc("Two rails that never meet are…","parallel",["perpendicular","intersecting","a ray"],"They stay the same distance apart."),
  ()=>numeric("What is the value of the 5 in 3,542?",500,"The 5 is in the hundreds place."),
  ()=>numeric("Round 1,648 to the nearest hundred.",1600,"Check the tens digit."),
  ()=>mc("Which is greater?","4,210",["4,120","equal","4,012"],"Compare place values from left to right."),
  ()=>numeric("You have ₱300 and earn ₱125. How much now?",425,"Add the amounts."),
  ()=>numeric("You have 900 screws and use 250. How many remain?",650,"Subtract."),
  ()=>numeric("6 brackets with 4 screws each need how many screws?",24,"6 groups of 4.")
 ]; return qs[i]();
}
function startPlayer(){const name=$("playerName").value.trim();if(!name)return;const key=name.toLowerCase().replace(/\s+/g," "),ps=loadProfiles();if(!ps[key])ps[key]=freshProfile(name);state.key=key;state.profile=ps[key];localStorage.setItem(PROFILE_KEY,JSON.stringify(ps));$("startScreen").classList.add("hidden");$("game").classList.remove("hidden");if(!state.profile.toolboxDone)showToolbox();else newJob();renderAll();}
function renderAll(){renderHeader();renderTiers();renderSkills();renderWorkshop();renderMaterials();}
function renderHeader(){const t=activeTier(),q=currentQuarter();$("playerPill").textContent="👷 "+state.profile.name;$("tierPill").textContent=TIERS[t].icon+" "+TIERS[t].name;$("quarterPill").textContent="📘 Quarter "+q;$("cashStat").textContent=peso(state.profile.cash);$("jobsStat").textContent=state.profile.jobs;$("masteredStat").textContent=masteredCount()+"/"+SKILLS.length;$("evidenceStat").textContent=totalEvidence();}
function renderTiers(){const cur=activeTier();$("bizPath").innerHTML=TIERS.map((t,i)=>{const unlocked=tierUnlocked(i),done=i<cur||(i===0&&state.profile.toolboxDone);return `<div class="tier ${i===cur?"current":done?"done":"locked"}"><strong>${t.icon} ${t.name}</strong><div class="small muted">${t.desc}</div><div class="small" style="margin-top:5px">${done?"✓ Completed":unlocked?"● Current":"🔒 Locked by math mastery"}</div></div>`}).join("");}
function renderSkills(){const q=currentQuarter(),cur=state.q?.skillId||chooseSkill().id;$("skillList").innerHTML=SKILLS.filter(s=>s.q===q).map(s=>{const st=getStat(s.id),a=Math.round(accuracy(s.id)*100),locked=!prereqsMet(s.id)&&!st.mastered;return `<div class="skill ${s.id===cur?"active":""} ${st.mastered?"mastered":""}"><div style="display:flex;justify-content:space-between;gap:8px"><strong>${s.n}</strong><span class="badge ${st.mastered?"mastered":"learn"}">${st.mastered?"MASTERED":locked?"PREREQ":"LEARNING"}</span></div><small>${st.possible?`${a}% independent evidence`:"Not independently assessed yet"}</small></div>`}).join("");}
function renderWorkshop(){const sk=state.q?S[state.q.skillId]:chooseSkill(),st=getStat(sk.id),a=Math.round(accuracy(sk.id)*100);$("focusSkill").textContent=sk.n;$("focusMastery").textContent=(st.possible?a:0)+"%";$("focusBar").style.width=(st.possible?a:0)+"%";$("focusEvidence").textContent=`${st.possible.toFixed(1)} independent evidence points`;$("adaptiveNote").textContent=st.mastered?"Mastered skills remain in later jobs for retention.":"Learn the current competency first. Guidance fades before independent mastery evidence is counted.";}
function renderMaterials(){const tools=state.profile.tools||[],inv=state.profile.inventory||{};$("materials").innerHTML=[...tools.slice(-4).map(t=>`<div class="material">${t.icon} <strong>${t.name}</strong></div>`),`<div class="material">🪵 Wood <strong>${inv.wood||0}</strong></div>`,`<div class="material">🔩 Screws <strong>${inv.screws||0}</strong></div>`].join("");}
function showToolbox(){$("jobArea").classList.add("hidden");$("completionCard").classList.add("hidden");$("toolboxIntro").classList.remove("hidden");const i=state.profile.toolboxIndex||0;if(i>=10){finishToolbox();return}state.q={...toolboxQuestion(i),toolbox:true};state.answered=false;state.hinted=false;const tool=TOOLBOX[i];$("toolboxIntro").innerHTML=`<div class="jobHeader"><div><span class="badge">TOOLBOX TUTORIAL ${i+1}/10</span><h2 style="margin:7px 0">Earn: ${tool[0]} ${tool[1]}</h2><p class="muted">Starter diagnostic only. These answers do not count toward curriculum mastery.</p></div><div class="jobIcon">${tool[0]}</div></div><div class="step"><div class="context">BASIC CHECK</div><div class="q">${state.q.text}</div><div id="tbAnswer"></div><div id="tbFeedback" class="feedback"></div><div class="row" style="margin-top:8px"><button id="tbHint" class="secondary">Hint</button><button id="tbNext" class="gold hidden">Next tool</button></div></div>`;renderInlineAnswer("tbAnswer",state.q,submitToolbox);$("tbHint").onclick=()=>{$("tbFeedback").textContent="Hint: "+state.q.hint;$("tbFeedback").className="feedback hintText";state.hinted=true};$("tbNext").onclick=()=>{state.profile.toolboxIndex++;saveProfiles();showToolbox();renderAll()};}
function renderInlineAnswer(containerId,q,handler){const el=$(containerId);if(q.type==="choice"){el.innerHTML=`<div class="choices">${q.options.map(o=>`<button class="choice" data-v="${String(o).replace(/"/g,"&quot;")}">${o}</button>`).join("")}</div>`;el.querySelectorAll("button").forEach(b=>b.onclick=()=>handler(b.dataset.v));}else{el.innerHTML=`<div class="answerRow"><input id="${containerId}Input" autocomplete="off"><button id="${containerId}Check">Check</button></div>`;const inp=$(containerId+"Input"),btn=$(containerId+"Check");btn.onclick=()=>handler(inp.value.trim());inp.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();handler(inp.value.trim())}});setTimeout(()=>inp.focus(),50);}}
function submitToolbox(v){if(state.answered)return;const correct=String(v).trim().toLowerCase()===String(state.q.answer).trim().toLowerCase();state.answered=true;if(!state.profile.toolboxDiagnostic)state.profile.toolboxDiagnostic=[];state.profile.toolboxDiagnostic.push({index:state.profile.toolboxIndex,correct,hinted:state.hinted});if(correct){const t=TOOLBOX[state.profile.toolboxIndex];state.profile.tools.push({icon:t[0],name:t[1]});$("tbFeedback").textContent=`Correct. ${t[0]} ${t[1]} added to your toolbox.`;$("tbFeedback").className="feedback good";}else{$("tbFeedback").textContent=`Not quite. Correct answer: ${state.q.answer}. This is diagnostic only and does not lower mastery.`;$("tbFeedback").className="feedback bad";}$("tbNext").classList.remove("hidden");saveProfiles();renderAll();}
function finishToolbox(){state.profile.toolboxDone=true;state.profile.tier=1;state.profile.cash+=100;saveProfiles();$("toolboxIntro").classList.add("hidden");$("completionCard").classList.remove("hidden");$("completionCard").innerHTML=`<h2>🧰 Toolbox Ready</h2><p>You now have the starter tools to accept paid house calls.</p><div class="notice">Next, Builder Quest will teach the first Grade 3 competency before asking you to work independently.</div><button id="firstJob">Accept First House Call</button>`;$("firstJob").onclick=()=>{$("completionCard").classList.add("hidden");newJob();renderAll()};renderAll();}
function learningPhase(skillId){const st=getStat(skillId);st.learning=st.learning||{guided:0,independent:0,independentCorrect:0};if(st.learning.guided<2)return "guided";return "independent";}
function currentCurriculumSkill(){const first=SKILLS.find(s=>!getStat(s.id).mastered);return first||SKILLS[SKILLS.length-1];}
function newJob(){if(!state.profile.toolboxDone){showToolbox();return}$("toolboxIntro").classList.add("hidden");$("completionCard").classList.add("hidden");$("jobArea").classList.remove("hidden");const tier=activeTier(),pool=JOBS[TIERS[tier].id]||JOBS.calls,meta=pick(pool),primary=currentCurriculumSkill(),phase=learningPhase(primary.id),mastered=SKILLS.filter(s=>getStat(s.id).mastered),steps=tier===1?3:tier===2?4:5;let skills=Array(steps).fill(primary.id);if(phase==="independent"&&mastered.length&&steps>3)skills[steps-1]=pick(mastered).id;const questions=skills.map(id=>{const target=id===primary.id,ctx=phase==="guided"&&target?"guided":pick(["direct","applied","reasoning"]),q=genQuestion(id,ctx==="guided"?"applied":ctx);return {...q,skillId:id,learningPhase:target?phase:"review"}});state.job={title:meta[0],desc:meta[1],icon:meta[2],tier,questions,index:0,earned:0,primary:primary.id,phase};$("jobType").textContent=TIERS[tier].name.toUpperCase();$("jobTitle").textContent=meta[0];$("jobDesc").textContent=meta[1];$("jobIcon").textContent=meta[2];showJobQuestion();}
function showJobQuestion(){const j=state.job;if(j.index>=j.questions.length){finishJob();return}state.q=j.questions[j.index];state.answered=false;state.hinted=false;const q=state.q,lesson=LESSONS[q.skillId];$("contextLabel").textContent=(q.learningPhase==="guided"?"LEARN & PRACTICE":q.learningPhase==="independent"?"INDEPENDENT WORK":"REVIEW")+" • "+S[q.skillId].n.toUpperCase();$("questionVisual").innerHTML=(q.learningPhase==="guided"?`<div class="notice"><strong>Foreman teaches:</strong> ${lesson.teach}<br><br><strong>Use this now:</strong> ${lesson.coach}</div>`:"")+(q.visual||"");$("questionText").textContent=q.text;$("feedback").textContent="";$("nextBtn").classList.add("hidden");$("hintBtn").disabled=false;$("jobProgress").style.width=(j.index/j.questions.length*100)+"%";$("jobMoney").textContent=peso(j.earned);if(q.type==="choice"){$("inputAnswer").classList.add("hidden");$("choices").classList.remove("hidden");$("choices").innerHTML=q.options.map(o=>`<button class="choice" data-v="${String(o).replace(/"/g,"&quot;")}">${o}</button>`).join("");$("choices").querySelectorAll("button").forEach(b=>b.onclick=()=>submitJob(b.dataset.v));}else{$("choices").classList.add("hidden");$("inputAnswer").classList.remove("hidden");$("answerInput").value="";$("checkBtn").disabled=false;setTimeout(()=>$("answerInput").focus(),50);}renderAll();}
function submitJob(v){if(state.answered)return;const correct=String(v).trim().toLowerCase()===String(state.q.answer).trim().toLowerCase();state.answered=true;const st=getStat(state.q.skillId);st.learning=st.learning||{guided:0,independent:0,independentCorrect:0};if(state.q.learningPhase==="guided"){st.learning.guided++;}else if(state.q.learningPhase==="independent"){st.learning.independent++;if(correct&&!state.hinted)st.learning.independentCorrect++;recordEvidence(state.q.skillId,correct,state.q.context||"applied",state.hinted);}else recordEvidence(state.q.skillId,correct,state.q.context||"applied",state.hinted);$("hintBtn").disabled=true;$("checkBtn").disabled=true;$("choices").querySelectorAll("button").forEach(b=>b.disabled=true);if(correct){const pay=state.q.learningPhase==="guided"?15:state.q.context==="reasoning"?35:25;state.job.earned+=pay;const m=pick(["wood","screws","brackets","paint"]);state.profile.inventory[m]=(state.profile.inventory[m]||0)+1;$("feedback").textContent=state.q.learningPhase==="guided"?"Correct. You used the method with the Foreman's guidance.":"Correct. This independent job decision adds mastery evidence.";$("feedback").className="feedback good";}else{$("feedback").textContent=state.q.learningPhase==="guided"?`Not yet. The answer is ${state.q.answer}. Use the Foreman's method again on the next job decision.`:`Not yet. The answer is ${state.q.answer}. Builder Quest will keep this competency in focus and may bring guidance back if needed.`;$("feedback").className="feedback bad";}$("nextBtn").classList.remove("hidden");saveProfiles();renderAll();}
$("checkBtn").onclick=()=>submitJob($("answerInput").value);$("answerInput").addEventListener("keydown",e=>{if(e.key!=="Enter")return;e.preventDefault();if(!state.answered)submitJob($("answerInput").value);else if(!$("nextBtn").classList.contains("hidden"))nextJobStep();});$("nextBtn").onclick=nextJobStep;function nextJobStep(){state.job.index++;showJobQuestion()}$("hintBtn").onclick=()=>{state.hinted=true;$("feedback").textContent="Hint: "+state.q.hint;$("feedback").className="feedback hintText"};
function finishJob(){const j=state.job,base=[0,900,2400,5200,9000][j.tier]||900,materialCost=Math.max(250,Math.round(base*.45)),feeSets={1:[450,700,1000],2:[1000,1500,2000],3:[1800,2500,3000],4:[2500,3000,4000]},fees=feeSets[j.tier]||[450,700,1000];$("jobArea").classList.add("hidden");$("completionCard").classList.remove("hidden");$("completionCard").innerHTML=`<span class="badge">JOB READY TO QUOTE</span><h2>${j.icon} ${j.title}</h2><p>The work is planned. Choose a realistic labor/service fee for this contract.</p><div class="materials"><div class="material"><small>Materials</small><strong>${peso(materialCost)}</strong></div><div class="material"><small>Job earnings</small><strong>${peso(j.earned)}</strong></div></div><p><strong>Choose your service fee:</strong></p><div class="choices" id="feeChoices">${fees.map((f,i)=>`<button class="choice" data-fee="${f}">${peso(f)} — ${i===0?"basic":i===1?"standard":"premium"}</button>`).join("")}</div>`;$("feeChoices").querySelectorAll("button").forEach(b=>b.onclick=()=>finalizeJob(materialCost,Number(b.dataset.fee)));}
function finalizeJob(materialCost,serviceFee){const j=state.job,quote=materialCost+serviceFee;state.profile.cash+=serviceFee;state.profile.jobs++;state.profile.portfolio=state.profile.portfolio||[];state.profile.portfolio.push({title:j.title,tier:TIERS[j.tier].name,date:new Date().toISOString().slice(0,10),skill:S[j.primary].n,materials:materialCost,serviceFee,quote,profit:serviceFee,mastered:getStat(j.primary).mastered});saveProfiles();$("completionCard").innerHTML=`<h2>Contract Complete</h2><div class="materials"><div class="material"><small>Materials</small><strong>${peso(materialCost)}</strong></div><div class="material"><small>Service fee</small><strong>${peso(serviceFee)}</strong></div><div class="material"><small>Customer quote</small><strong>${peso(quote)}</strong></div><div class="material"><small>Business profit</small><strong>${peso(serviceFee)}</strong></div></div><div class="notice">Project saved to your Builder Portfolio. ${getStat(j.primary).mastered?"This competency is now mastered and will remain in future jobs for review.":"The current competency remains in focus until mastery evidence is sufficient."}</div><button id="anotherJob">Accept Next Contract</button>`;$("anotherJob").onclick=()=>{$("completionCard").classList.add("hidden");newJob();renderAll()};renderAll();}
