function qkey(id,family,vals){return `${id}:${family}:${vals.join('-')}`}
function unseen(id,maker){state.profile.seenQuestions=state.profile.seenQuestions||{};state.profile.seenQuestions[id]=state.profile.seenQuestions[id]||[];let q;for(let i=0;i<30;i++){q=maker();if(!state.profile.seenQuestions[id].includes(q.key))break}state.profile.seenQuestions[id].push(q.key);if(state.profile.seenQuestions[id].length>80)state.profile.seenQuestions[id].shift();return q}
function weakestComponent(id){const sk=S[id],st=getStat(id);return sk.comps.slice().sort((a,b)=>{const A=st.components[a]||{independent:0,correct:0},B=st.components[b]||{independent:0,correct:0};if(A.independent!==B.independent)return A.independent-B.independent;const ar=A.independent?A.correct/A.independent:0,br=B.independent?B.correct/B.independent:0;return ar-br})[0]}
function genQuestion(skillId,context){const comp=weakestComponent(skillId),direct=context==="direct";return unseen(skillId,()=>{
 if(skillId==="q1_area"){
  const l=rand(2,12),w=rand(2,10),a=l*w,family=pick(["panel","floor","table","cabinet","shelf"]);
  if(comp==="square_units")return numeric(`A ${family} surface is covered by ${l} rows of ${w} equal square tiles. How many square tiles cover it?`,a,"Count equal square units by multiplying rows × squares in each row.",context,"",comp,qkey(skillId,family,[l,w,"sq"]));
  if(comp==="formula")return numeric(`A rectangular ${family} is ${l} cm long and ${w} cm wide. What is its area?`,a,"Area of a rectangle = length × width.",context,"",comp,qkey(skillId,family,[l,w,"f"]));
  if(comp==="units")return mc(`A ${l} cm by ${w} cm cabinet panel has area ${a}. Which unit correctly labels that area?`,`${a} cm²`,[`${a} cm`,`${a} m²`,`${a} m`],"Area uses square units.",context,"",comp,qkey(skillId,family,[l,w,"u"]));
  return numeric(`A carpenter must cover a ${l} m by ${w} m rectangular ${family}. Each tile covers 1 m². How many tiles are needed?`,a,"Decide what surface must be covered, then find its area.",context,"",comp,qkey(skillId,family,[l,w,"app"]));
 }
 if(skillId==="q1_lines"){const rel=pick([["parallel","two shelf rails that never meet"],["perpendicular","a wall post meeting a beam at a square corner"],["intersecting","two braces crossing"]]);return mc(`A blueprint shows ${rel[1]}. What relationship is shown?`,rel[0],["parallel","perpendicular","intersecting"].filter(x=>x!==rel[0]),"Look at whether and how the lines meet.",context,"",comp,qkey(skillId,"rel",[rel[0],rand(1,999)]))}
 if(skillId==="q1_numbers"){const n=rand(1000,9999);return numeric(`A lumber shipment is labeled ${n.toLocaleString()}. Enter the number without commas.`,n,"Read thousands, hundreds, tens, and ones.",context,"",comp,qkey(skillId,"read",[n]))}
 if(skillId==="q1_ordinals"){const n=rand(4,100),s=n%100>=11&&n%100<=13?"th":n%10===1?"st":n%10===2?"nd":n%10===3?"rd":"th";return mc(`Your delivery is number ${n} in the queue. Which ordinal shows its position?`,`${n}${s}`,[`${n+1}th`,`${n-1}th`,`${n}st`],"Ordinal numbers show position.",context,"",comp,qkey(skillId,"ord",[n]))}
 if(skillId==="q1_place"){const n=rand(1000,9999),places=[["thousands",1000],["hundreds",100],["tens",10],["ones",1]],p=pick(places),d=Math.floor(n/p[1])%10;return numeric(`In stock code ${n}, what digit is in the ${p[0]} place?`,d,"Locate the requested place.",context,"",comp,qkey(skillId,"place",[n,p[1]]))}
 if(skillId==="q1_round"){const n=rand(1000,9999),base=pick([10,100,1000]);return numeric(`Round the supplier count ${n} to the nearest ${base}.`,Math.round(n/base)*base,"Look one digit to the right of the rounding place.",context,"",comp,qkey(skillId,"round",[n,base]))}
 if(skillId==="q1_compare"){const a=rand(1000,9999),b=rand(1000,9999),ans=a>b?">":a<b?"<":"=";return mc(`Compare stock counts: ${a} __ ${b}.`,ans,["<",">","="].filter(x=>x!==ans),"Compare from the largest place.",context,"",comp,qkey(skillId,"compare",[a,b]))}
 if(skillId==="q2_mass"){const x=pick([["hammer","kg"],["box of nails","g"],["tiny screw","mg"]]);return mc(`Which unit is sensible for the mass of a ${x[0]}?`,x[1],["g","kg","mg"].filter(v=>v!==x[1]),"Match the unit to the object's mass.",context,"",comp,qkey(skillId,"unit",[x[0],rand(1,999)]))}
 if(skillId==="q2_capacity"){const x=pick([["paint can","L"],["glue bottle","mL"],["water jug","L"]]);return mc(`Which unit is sensible for the capacity of a ${x[0]}?`,x[1],["L","mL"].filter(v=>v!==x[1]),"Match unit to container size.",context,"",comp,qkey(skillId,"unit",[x[0],rand(1,999)]))}
 if(skillId==="q2_money"){const p=rand(120,9800);return numeric(`A hardware receipt totals ${peso(p)}. Enter the peso amount.`,p,"Read the peso value.",context,"",comp,qkey(skillId,"money",[p]))}
 if(skillId==="q2_add"||skillId==="q2_addprob"){const a=rand(500,4500),b=rand(400,4500);if(a+b>9999)return genQuestion(skillId,context);return numeric(`Wood costs ${peso(a)} and hardware costs ${peso(b)}. What is the total?`,a+b,"Add the costs by place value.",context,"",comp,qkey(skillId,"add",[a,b]))}
 if(skillId==="q2_addest"){const a=rand(1100,4700),b=rand(900,3900);return numeric(`Estimate ${a} + ${b} by rounding each to the nearest hundred.`,Math.round(a/100)*100+Math.round(b/100)*100,"Round both, then add.",context,"",comp,qkey(skillId,"est",[a,b]))}
 if(skillId==="q2_sub"){const a=rand(3000,9999),b=rand(500,a-100);return numeric(`You stocked ${a} screws and used ${b}. How many remain?`,a-b,"Subtract used stock from starting stock.",context,"",comp,qkey(skillId,"sub",[a,b]))}
 if(skillId==="q2_subest"){const a=rand(4000,9999),b=rand(500,3500);return numeric(`Estimate ${a} − ${b} by rounding both to the nearest hundred.`,Math.round(a/100)*100-Math.round(b/100)*100,"Round, then subtract.",context,"",comp,qkey(skillId,"est",[a,b]))}
 if(skillId==="q2_mixed"){const s=rand(40,80),a=rand(5,15),b=rand(5,15),c=rand(3,10);return numeric(`Inventory starts at ${s} boards. Buy ${a}, use ${b}, then receive ${c}. How many now?`,s+a-b+c,"Follow events in order.",context,"",comp,qkey(skillId,"mixed",[s,a,b,c]))}
 if(skillId==="q3_data"||skillId==="q3_graph"){const v=[rand(2,9),rand(2,9),rand(2,9)],labels=["Shelves","Doors","Tables"],mx=Math.max(...v),idx=v.indexOf(mx),visual=`<div>${v.map((x,i)=>`<div class="small">${labels[i]}: ${x}</div>`).join("")}</div>`;return mc("Which job type has the greatest frequency?",labels[idx],labels.filter(x=>x!==labels[idx]),"Compare the frequencies.",context,visual,comp,qkey(skillId,"data",v))}
 if(skillId==="q3_probability")return mc("A bin has 8 wood screws and 2 brass screws. Which is more likely to be picked?","wood screw",["brass screw","equally likely","impossible"],"Compare how many of each are present.",context,"",comp,qkey(skillId,"prob",[rand(1,9999)]));
 if(skillId==="q3_facts"){const map={six:6,seven:7,eight:8,nine:9},a=map[comp]||pick([6,7,8,9]),b=rand(2,10);return numeric(`${b} shelf brackets need ${a} screws each. How many screws?`,a*b,"Use equal groups.",context,"",comp,qkey(skillId,"facts",[a,b]))}
 if(skillId==="q3_props"){const a=rand(2,9),b=rand(2,9);if(comp==="identity")return numeric(`${a} × 1 = ?`,a,"Identity keeps the number.",context,"",comp,qkey(skillId,"id",[a]));if(comp==="zero")return numeric(`${a} × 0 = ?`,0,"Any number times zero is zero.",context,"",comp,qkey(skillId,"zero",[a]));return mc(`Which expression has the same product as ${a} × ${b}?`,`${b} × ${a}`,[`${a}+${b}`,`${a}×${b+1}`,`${a}-${b}`],"Think about multiplication properties.",context,"",comp,qkey(skillId,"prop",[a,b,comp]))}
 if(skillId==="q3_mult"||skillId==="q3_multprob"){const a=rand(21,399),b=rand(2,9);if(a*b>9999)return genQuestion(skillId,context);return numeric(`${b} bundles contain ${a} fasteners each. How many fasteners altogether?`,a*b,"Multiply the groups.",context,"",comp,qkey(skillId,"mult",[a,b]))}
 if(skillId==="q3_estprod"){const a=rand(21,189),b=rand(11,49),ra=Math.round(a/10)*10,rb=Math.round(b/10)*10;return numeric(`Estimate ${a} × ${b} by rounding both factors to the nearest 10.`,ra*rb,"Round, then multiply.",context,"",comp,qkey(skillId,"est",[a,b]))}
 if(skillId==="q3_patterns"){const start=rand(2,20),inc=rand(2,8),seq=[start,start+inc,start+inc*2,start+inc*3];return numeric(`Cut lengths follow ${seq.join(", ")}, __. What comes next?`,start+inc*4,"Find the change from term to term.",context,"",comp,qkey(skillId,"pattern",[start,inc]))}
 if(skillId==="q4_divconcept"||skillId==="q4_div"){const d=rand(2,9),q=rand(2,30),r=skillId==="q4_div"?rand(0,d-1):0,n=d*q+r;return numeric(`${n} screws are packed in groups of ${d}. How many complete groups?`,Math.floor(n/d),"Use the related multiplication fact.",context,"",comp,qkey(skillId,"div",[n,d]))}
 if(skillId==="q4_estquot"){const d=pick([20,30,40,50]),q=rand(3,9),n=d*q+rand(-8,8),rounded=Math.round(n/10)*10;return numeric(`Estimate ${n} ÷ ${d} after rounding ${n} to the nearest 10.`,Math.round(rounded/d),"Round to a friendly number, then divide.",context,"",comp,qkey(skillId,"est",[n,d]))}
 if(skillId==="q4_divprob"){const d=pick([6,7,8,9]),q=rand(10,40),n=d*q;return numeric(`${peso(n)} of materials is shared equally across ${d} rooms. Cost per room?`,q,"Divide total cost by rooms.",context,"",comp,qkey(skillId,"money",[n,d]))}
 if(skillId==="q4_fracrep"){const den=pick([2,3,4,5]),num=rand(den,den*2+2);return mc(`Which fraction represents ${num} equal parts when one whole has ${den} parts?`,`${num}/${den}`,[`${den}/${num}`,`${num-1}/${den}`,`${num}/${den+1}`],"Numerator counts parts; denominator gives parts per whole.",context,"",comp,qkey(skillId,"frac",[num,den]))}
 if(skillId==="q4_fracops"){const den=pick([3,4,5,6,8]),a=rand(1,den-1),b=rand(1,den-a);return mc(`${a}/${den} m plus ${b}/${den} m equals?`,`${a+b}/${den}`,[`${a+b}/${den*2}`,`${Math.abs(a-b)}/${den}`,`${a+b}/${den+1}`],"Keep the denominator and add numerators.",context,"",comp,qkey(skillId,"fracop",[a,b,den]))}
 if(skillId==="q4_translation")return mc("A template slides 3 squares right and 2 up. Which describes the movement?","right 3, up 2",["left 3, up 2","right 2, up 3","right 3, down 2"],"Track horizontal then vertical.",context,"",comp,qkey(skillId,"slide",[rand(1,9999)]));
 return mc("Which object most clearly has a vertical line of symmetry?","a centered rectangular door",["an L-shaped bracket","a stair-step shape","an off-center shelf"],"Imagine folding it down the middle.",context,"",comp,qkey(skillId,"sym",[rand(1,9999)]));
 })}
