function qkey(id,family,vals){return `${id}:${family}:${vals.join('-')}`}
function unseen(id,maker){state.profile.seenQuestions=state.profile.seenQuestions||{};state.profile.seenQuestions[id]=state.profile.seenQuestions[id]||[];let q;for(let i=0;i<40;i++){q=maker();if(!state.profile.seenQuestions[id].includes(q.key))break}state.profile.seenQuestions[id].push(q.key);if(state.profile.seenQuestions[id].length>120)state.profile.seenQuestions[id].shift();return q}
function weakestComponent(id){const sk=S[id],st=getStat(id);return sk.comps.slice().sort((a,b)=>{const A=st.components[a]||{independent:0,correct:0},B=st.components[b]||{independent:0,correct:0};if(A.independent!==B.independent)return A.independent-B.independent;const ar=A.independent?A.correct/A.independent:0,br=B.independent?B.correct/B.independent:0;return ar-br})[0]}
function genQuestion(skillId,context){const comp=weakestComponent(skillId);return unseen(skillId,()=>{
 if(skillId==="q1_area"){
  const l=rand(2,12),w=rand(2,10),a=l*w,obj=pick(["tabletop","cabinet panel","shelf panel","floor section","workbench top","door panel","plywood sheet","storage lid"]),unit=pick(["cm","m"]),family=pick(["count","formula","label","cover","compare","missing","material","reverse"]);
  if(comp==="square_units"){
   if(family==="compare"){const l2=Math.max(2,l-1),w2=w+1,a2=l2*w2,ans=a>=a2?"first":"second";return mc(`Two panels are tiled with equal square units. The first has ${l} rows of ${w}; the second has ${l2} rows of ${w2}. Which covers more area?`,ans,["first","second","same"].filter(x=>x!==ans),"Compare the number of square units covering each surface.",context,"",comp,qkey(skillId,"sq-compare",[l,w,l2,w2]))}
   return numeric(`A ${obj} is covered by ${l} rows of ${w} equal square tiles. How many square tiles cover it?`,a,"Count equal square units by multiplying rows × squares in each row.",context,"",comp,qkey(skillId,"sq-count",[obj,l,w]));
  }
  if(comp==="formula"){
   if(family==="missing"){const side=pick(["length","width"]),known=side==="length"?w:l,total=a,ans=side==="length"?l:w;return numeric(`A rectangular ${obj} has area ${total} ${unit}². Its ${side==="length"?"width":"length"} is ${known} ${unit}. What is the ${side}?`,ans,"Use area = length × width, then find the missing factor.",context,"",comp,qkey(skillId,"formula-missing",[obj,total,known,side]))}
   return numeric(`A rectangular ${obj} is ${l} ${unit} long and ${w} ${unit} wide. What is its area?`,a,"Area of a rectangle = length × width.",context,"",comp,qkey(skillId,"formula",[obj,l,w,unit]));
  }
  if(comp==="units")return mc(`A ${l} ${unit} by ${w} ${unit} ${obj} has area ${a}. Which label is correct?`,`${a} ${unit}²`,[`${a} ${unit}`,`${a} ${unit}³`,`${a*2} ${unit}²`],"Area uses square units.",context,"",comp,qkey(skillId,"units",[obj,l,w,unit]));
  if(family==="material"){const stock=a+rand(3,30);return numeric(`A carpenter has ${stock} one-square-${unit} panels in stock. A ${obj} needs to cover ${l} by ${w} ${unit}. How many panels will remain after the job?`,stock-a,"Find the area needed, then subtract it from inventory.",context,"",comp,qkey(skillId,"application-stock",[obj,l,w,stock,unit]))}
  if(family==="reverse"){const packs=rand(2,6),per=rand(4,12),need=packs*per;return numeric(`A ${obj} needs ${need} square ${unit} of covering. Covering comes in packs of ${per} square ${unit}. How many full packs are needed?`,packs,"Connect the required area to the amount supplied per pack.",context,"",comp,qkey(skillId,"application-pack",[obj,need,per,unit]))}
  return numeric(`A carpenter must cover a ${l} ${unit} by ${w} ${unit} rectangular ${obj}. Each tile covers 1 ${unit}². How many tiles are needed?`,a,"Decide what surface must be covered, then find its area.",context,"",comp,qkey(skillId,"application-cover",[obj,l,w,unit]));
 }
 if(skillId==="q1_lines"){
  if(comp==="objects"){const item=pick([["one endpoint and continues in one direction","ray"],["two endpoints","segment"],["continues in both directions","line"],["marks one exact location","point"]]);return mc(`On a blueprint, a mark ${item[0]}. What is it?`,item[1],["point","line","segment","ray"].filter(x=>x!==item[1]),"Use endpoints and direction to identify the object.",context,"",comp,qkey(skillId,"object",[item[1],pick(["beam","rail","edge","mark"])]))}
  if(comp==="equal_segments"){const a=rand(2,12),b=rand(2,12),same=a===b?"equal":"not equal";return mc(`Two cut segments measure ${a} cm and ${b} cm. Are their lengths equal?`,same,["equal","not equal"].filter(x=>x!==same),"Compare the segment lengths.",context,"",comp,qkey(skillId,"equal",[a,b]))}
  const rel=pick([["parallel","two shelf rails stay the same distance apart"],["perpendicular","a wall post meets a beam at a square corner"],["intersecting","two braces cross at a non-square angle"]]);return mc(`A blueprint shows ${rel[1]}. What relationship is shown?`,rel[0],["parallel","perpendicular","intersecting"].filter(x=>x!==rel[0]),"Look at whether and how the lines meet.",context,"",comp,qkey(skillId,"relationship",[rel[0],pick(["shelf","frame","roof","cabinet"])]))
 }
 if(skillId==="q1_numbers"){const n=rand(1000,9999);if(comp==="represent"){const th=Math.floor(n/1000),h=Math.floor(n/100)%10,t=Math.floor(n/10)%10,o=n%10;return mc(`Which expanded form matches ${n.toLocaleString()}?`,`${th*1000}+${h*100}+${t*10}+${o}`,[`${th*100}+${h*10}+${t}+${o}`,`${th*1000}+${h*10}+${t*100}+${o}`,`${th*1000+h*100+t*10+o+10}`],"Break the number into place values.",context,"",comp,qkey(skillId,"expanded",[n]))}return numeric(`A lumber shipment is labeled ${n.toLocaleString()}. Enter the number without commas.`,n,"Read thousands, hundreds, tens, and ones.",context,"",comp,qkey(skillId,"read",[n]))}
 if(skillId==="q1_ordinals"){const n=rand(4,100),suffix=n%100>=11&&n%100<=13?"th":n%10===1?"st":n%10===2?"nd":n%10===3?"rd":"th";return mc(`Your delivery is number ${n} in the queue. Which ordinal shows its position?`,`${n}${suffix}`,[`${n+1}th`,`${n-1}th`,`${n}st`],"Ordinal numbers show position.",context,"",comp,qkey(skillId,"ordinal",[n]))}
 if(skillId==="q1_place"){const n=rand(1000,9999),places=[["thousands",1000],["hundreds",100],["tens",10],["ones",1]],p=pick(places),d=Math.floor(n/p[1])%10;if(comp==="value")return numeric(`In stock code ${n}, what is the value of the digit ${d} in the ${p[0]} place?`,d*p[1],"Digit value equals the digit times its place.",context,"",comp,qkey(skillId,"value",[n,p[1]]));return numeric(`In stock code ${n}, what digit is in the ${p[0]} place?`,d,"Locate the requested place.",context,"",comp,qkey(skillId,"place",[n,p[1]]))}
 if(skillId==="q1_round"){const n=rand(1000,9999),base=pick([10,100,1000]);return numeric(`Round the supplier count ${n} to the nearest ${base}.`,Math.round(n/base)*base,"Look one digit to the right of the rounding place.",context,"",comp,qkey(skillId,"round",[n,base]))}
 if(skillId==="q1_compare"){const a=rand(1000,9999),b=rand(1000,9999);if(comp==="order"){const c=rand(1000,9999),arr=[a,b,c].sort((x,y)=>x-y);return mc(`Which list orders these stock counts from least to greatest: ${a}, ${b}, ${c}?`,arr.join(", "),[[...arr].reverse().join(", "),[arr[1],arr[0],arr[2]].join(", "),[arr[0],arr[2],arr[1]].join(", ")],"Compare from the thousands place left to right.",context,"",comp,qkey(skillId,"order",[a,b,c]))}const ans=a>b?">":a<b?"<":"=";return mc(`Compare stock counts: ${a} __ ${b}.`,ans,["<",">","="].filter(x=>x!==ans),"Compare from the largest place.",context,"",comp,qkey(skillId,"compare",[a,b]))}
 if(skillId==="q2_mass"){if(comp==="compare"){const a=rand(200,950),b=rand(200,950),ans=a>b?"first":"second";return mc(`Two hardware boxes weigh ${a} g and ${b} g. Which is heavier?`,ans,["first","second","same"].filter(x=>x!==ans),"Compare amounts using the same unit.",context,"",comp,qkey(skillId,"compare",[a,b]))}if(comp==="estimate"){const obj=pick([["hammer",800,"g"],["nail",5,"g"],["toolbox",4,"kg"]]);return mc(`Which is the most sensible estimate for the mass of a ${obj[0]}?`,`${obj[1]} ${obj[2]}`,[`${obj[1]*10} ${obj[2]}`,`${Math.max(1,Math.floor(obj[1]/10))} ${obj[2]}`,`${obj[1]} ${obj[2]==="kg"?"mg":"kg"}`],"Use a reasonable real-world estimate.",context,"",comp,qkey(skillId,"estimate",[obj[0],obj[1],obj[2]]))}const x=pick([["hammer","kg"],["box of nails","g"],["tiny screw","mg"],["wood plank","kg"],["washer","g"]]);return mc(`Which unit is sensible for the mass of a ${x[0]}?`,x[1],["g","kg","mg"].filter(v=>v!==x[1]),"Match the unit to the object's mass.",context,"",comp,qkey(skillId,"unit",[x[0],x[1]]))}
 if(skillId==="q2_capacity"){if(comp==="compare"){const a=rand(200,950),b=rand(200,950),ans=a>b?"first":"second";return mc(`Two glue bottles hold ${a} mL and ${b} mL. Which holds more?`,ans,["first","second","same"].filter(x=>x!==ans),"Compare amounts in the same unit.",context,"",comp,qkey(skillId,"compare",[a,b]))}if(comp==="estimate"){const x=pick([["paint can",4,"L"],["glue bottle",250,"mL"],["water jug",2,"L"]]);return mc(`Which is a sensible capacity for a ${x[0]}?`,`${x[1]} ${x[2]}`,[`${x[1]*10} ${x[2]}`,`${Math.max(1,Math.floor(x[1]/10))} ${x[2]}`,`${x[1]} ${x[2]==="L"?"mL":"L"}`],"Use a realistic estimate.",context,"",comp,qkey(skillId,"estimate",[x[0],x[1],x[2]]))}const x=pick([["paint can","L"],["glue bottle","mL"],["water jug","L"],["small varnish bottle","mL"]]);return mc(`Which unit is sensible for the capacity of a ${x[0]}?`,x[1],["L","mL"].filter(v=>v!==x[1]),"Match unit to container size.",context,"",comp,qkey(skillId,"unit",[x[0],x[1]]))}
 if(skillId==="q2_money"){const p=rand(120,9800);return numeric(`A hardware receipt totals ${peso(p)}. Enter the peso amount.`,p,"Read the peso value.",context,"",comp,qkey(skillId,"money",[p]))}
 if(skillId==="q2_add"||skillId==="q2_addprob"){const a=rand(500,4500),b=rand(400,4500);if(a+b>9999)return genQuestion(skillId,context);return numeric(`Wood costs ${peso(a)} and hardware costs ${peso(b)}. What is the total?`,a+b,"Add the costs by place value.",context,"",comp,qkey(skillId,"add",[a,b,context]))}
 if(skillId==="q2_addest"){const a=rand(1100,4700),b=rand(900,3900);return numeric(`Estimate ${a} + ${b} by rounding each to the nearest hundred.`,Math.round(a/100)*100+Math.round(b/100)*100,"Round both, then add.",context,"",comp,qkey(skillId,"estimate-sum",[a,b]))}
 if(skillId==="q2_sub"){const a=rand(3000,9999),b=rand(500,a-100);return numeric(`You stocked ${a} screws and used ${b}. How many remain?`,a-b,"Subtract used stock from starting stock.",context,"",comp,qkey(skillId,"subtract",[a,b,context]))}
 if(skillId==="q2_subest"){const a=rand(4000,9999),b=rand(500,3500);return numeric(`Estimate ${a} − ${b} by rounding both to the nearest hundred.`,Math.round(a/100)*100-Math.round(b/100)*100,"Round, then subtract.",context,"",comp,qkey(skillId,"estimate-difference",[a,b]))}
 if(skillId==="q2_mixed"){const s=rand(40,80),a=rand(5,15),b=rand(5,15),c=rand(3,10);return numeric(`Inventory starts at ${s} boards. Buy ${a}, use ${b}, then receive ${c}. How many now?`,s+a-b+c,"Follow events in order.",context,"",comp,qkey(skillId,"mixed",[s,a,b,c]))}
 if(skillId==="q3_data"||skillId==="q3_graph"){const v=[rand(2,12),rand(2,12),rand(2,12),rand(2,12)],labels=["Shelves","Doors","Tables","Cabinets"],visual=`<div>${v.map((x,i)=>`<div class="small">${labels[i]}: ${"▮".repeat(x)} ${x}</div>`).join("")}</div>`;if(comp==="solve"){const hi=Math.max(...v),lo=Math.min(...v);return numeric("How many more jobs are in the largest category than the smallest?",hi-lo,"Find the largest and smallest frequencies, then subtract.",context,visual,comp,qkey(skillId,"graph-difference",v))}const mx=Math.max(...v),idx=v.indexOf(mx);return mc("Which job type has the greatest frequency?",labels[idx],labels.filter(x=>x!==labels[idx]),"Compare the frequencies.",context,visual,comp,qkey(skillId,"graph-max",v))}
 if(skillId==="q3_probability"){const a=rand(2,10),b=rand(1,10);if(comp==="certain_impossible")return mc(`A box contains only ${a} wood screws. Picking a brass screw is…`,"impossible",["certain","more likely","equally likely"],"An outcome not present in the box cannot happen.",context,"",comp,qkey(skillId,"impossible",[a]));const ans=a>b?"wood screw":a<b?"brass screw":"equally likely";return mc(`A bin has ${a} wood screws and ${b} brass screws. What is more likely to be picked?`,ans,["wood screw","brass screw","equally likely"].filter(x=>x!==ans),"Compare how many of each are present.",context,"",comp,qkey(skillId,"likelihood",[a,b]))}
 if(skillId==="q3_facts"){const map={six:6,seven:7,eight:8,nine:9},a=map[comp]||pick([6,7,8,9]),b=rand(2,10);return numeric(`${b} shelf brackets need ${a} screws each. How many screws?`,a*b,"Use equal groups.",context,"",comp,qkey(skillId,"facts",[a,b,context]))}
 if(skillId==="q3_props"){const a=rand(2,9),b=rand(2,9),c=rand(2,5);if(comp==="identity")return numeric(`${a} × 1 = ?`,a,"Identity keeps the number.",context,"",comp,qkey(skillId,"identity",[a]));if(comp==="zero")return numeric(`${a} × 0 = ?`,0,"Any number times zero is zero.",context,"",comp,qkey(skillId,"zero",[a]));if(comp==="commutative")return mc(`Which expression has the same product as ${a} × ${b}?`,`${b} × ${a}`,[`${a}+${b}`,`${a}×${b+1}`,`${a}-${b}`],"Factors may switch order without changing the product.",context,"",comp,qkey(skillId,"commutative",[a,b]));if(comp==="associative")return mc(`Which expression matches (${a} × ${b}) × ${c}?`,`${a} × (${b} × ${c})`,[`${a+b} × ${c}`,`${a} × (${b}+${c})`,`(${a}+${b}) × ${c}`],"Grouping factors may change without changing their order.",context,"",comp,qkey(skillId,"associative",[a,b,c]));return mc(`Which breaks apart ${a} × ${b+c} correctly?`,`${a}×${b} + ${a}×${c}`,[`${a+b}×${c}`,`${a}×${b} + ${c}`,`${a+b+c}`],"Distribute the factor to both parts.",context,"",comp,qkey(skillId,"distributive",[a,b,c]))}
 if(skillId==="q3_mult"||skillId==="q3_multprob"){const a=rand(21,399),b=rand(2,9);if(a*b>9999)return genQuestion(skillId,context);return numeric(`${b} bundles contain ${a} fasteners each. How many fasteners altogether?`,a*b,"Multiply the groups.",context,"",comp,qkey(skillId,"multiply",[a,b,context]))}
 if(skillId==="q3_estprod"){const a=rand(21,189),b=rand(11,49),ra=Math.round(a/10)*10,rb=Math.round(b/10)*10;return numeric(`Estimate ${a} × ${b} by rounding both factors to the nearest 10.`,ra*rb,"Round, then multiply.",context,"",comp,qkey(skillId,"estimate-product",[a,b]))}
 if(skillId==="q3_patterns"){const start=rand(2,20),inc=rand(2,8),dir=pick([1,-1]),safe=dir===1?start:start+inc*5,seq=[safe,safe+dir*inc,safe+dir*inc*2,safe+dir*inc*3];if(comp==="explain")return mc(`Pattern: ${seq.join(", ")}. What is the rule?`,`${dir===1?"add":"subtract"} ${inc}`,[`${dir===1?"subtract":"add"} ${inc}`,`${dir===1?"add":"subtract"} ${inc+1}`,"double each term"],"Find the same change between consecutive terms.",context,"",comp,qkey(skillId,"pattern-rule",[safe,inc,dir]));return numeric(`Cut lengths follow ${seq.join(", ")}, __. What comes next?`,safe+dir*inc*4,"Find the change from term to term.",context,"",comp,qkey(skillId,"pattern-next",[safe,inc,dir]))}
 if(skillId==="q4_divconcept"||skillId==="q4_div"){const d=rand(2,9),q=rand(2,30),r=skillId==="q4_div"&&comp==="remainder"?rand(1,d-1):0,n=d*q+r;if(comp==="inverse")return mc(`${d} × ${q} = ${d*q}. Which related division fact is correct?`,`${d*q} ÷ ${d} = ${q}`,[`${d*q} ÷ ${q} = ${d+1}`,`${d+q} ÷ ${d} = ${q}`,`${d*q} ÷ ${d+1} = ${q}`],"Division reverses multiplication.",context,"",comp,qkey(skillId,"inverse",[d,q]));if(comp==="remainder")return mc(`${n} screws are packed in groups of ${d}. What is the result?`,`${q} remainder ${r}`,[`${q+1} remainder 0`,`${q} remainder ${Math.max(0,r-1)}`,`${q-1} remainder ${r}`],"Make complete equal groups, then count what is left.",context,"",comp,qkey(skillId,"remainder",[n,d]));return numeric(`${n} screws are packed in groups of ${d}. How many complete groups?`,Math.floor(n/d),"Use the related multiplication fact.",context,"",comp,qkey(skillId,"division",[n,d,context]))}
 if(skillId==="q4_estquot"){const d=pick([20,30,40,50]),q=rand(3,9),friendly=d*q,delta=pick([-9,-7,-4,4,7,9]),n=friendly+delta;return numeric(`Estimate ${n} ÷ ${d} by using the nearby friendly dividend ${friendly}.`,q,"Choose a nearby dividend that divides evenly by the divisor.",context,"",comp,qkey(skillId,"estimate-quotient",[n,d,friendly]))}
 if(skillId==="q4_divprob"){const d=pick([6,7,8,9]),q=rand(10,40),n=d*q;return numeric(`${peso(n)} of materials is shared equally across ${d} rooms. Cost per room?`,q,"Divide total cost by rooms.",context,"",comp,qkey(skillId,"division-money",[n,d]))}
 if(skillId==="q4_fracrep"){const den=pick([2,3,4,5,6,8]),num=comp==="equal_one"?den:rand(den+1,den*2+2);return mc(`Which fraction represents ${num} equal parts when one whole has ${den} parts?`,`${num}/${den}`,[`${den}/${num}`,`${num-1}/${den}`,`${num}/${den+1}`],"Numerator counts parts; denominator gives parts per whole.",context,"",comp,qkey(skillId,"fraction-represent",[num,den]))}
 if(skillId==="q4_fracops"){const den=pick([3,4,5,6,8]),a=rand(1,den-1),b=rand(1,den-1);if(comp==="subtraction"){const hi=Math.max(a,b),lo=Math.min(a,b);return mc(`${hi}/${den} m minus ${lo}/${den} m equals?`,`${hi-lo}/${den}`,[`${hi+lo}/${den}`,`${hi-lo}/${den*2}`,`${Math.max(0,hi-lo-1)}/${den}`],"Keep the denominator and subtract numerators.",context,"",comp,qkey(skillId,"fraction-subtract",[hi,lo,den]))}return mc(`${a}/${den} m plus ${b}/${den} m equals?`,`${a+b}/${den}`,[`${a+b}/${den*2}`,`${Math.abs(a-b)}/${den}`,`${a+b}/${den+1}`],"Keep the denominator and add numerators.",context,"",comp,qkey(skillId,"fraction-add",[a,b,den]))}
 if(skillId==="q4_translation"){const h=rand(1,6),v=rand(1,6),hd=pick(["right","left"]),vd=pick(["up","down"]);return mc(`A template slides ${h} squares ${hd} and ${v} squares ${vd}. Which describes the movement?`,`${hd} ${h}, ${vd} ${v}`,[`${hd==="right"?"left":"right"} ${h}, ${vd} ${v}`,`${hd} ${v}, ${vd} ${h}`,`${hd} ${h}, ${vd==="up"?"down":"up"} ${v}`],"Track horizontal and vertical movement separately.",context,"",comp,qkey(skillId,"translation",[h,v,hd,vd]))}
 const sym=pick([["a centered rectangular door","vertical"],["a square tile","vertical and horizontal"],["an isosceles roof front","vertical"]]);return mc(`Which symmetry description fits ${sym[0]}?`,sym[1],["none","horizontal only","diagonal only","vertical only"].filter(x=>x!==sym[1]),"Imagine folding the figure along possible mirror lines.",context,"",comp,qkey(skillId,"symmetry",[sym[0],sym[1]]));
 })}
