function qkey(id,family,vals){return `${id}:${family}:${vals.join('-')}`}
function unseen(id,maker){
  state.profile.seenQuestions=state.profile.seenQuestions||{};
  state.profile.seenQuestions[id]=state.profile.seenQuestions[id]||[];
  let q;
  for(let i=0;i<60;i++){
    q=maker();
    if(!state.profile.seenQuestions[id].includes(q.key))break;
  }
  state.profile.seenQuestions[id].push(q.key);
  if(state.profile.seenQuestions[id].length>160)state.profile.seenQuestions[id].shift();
  return q;
}
function weakestComponent(id){
  const sk=S[id],st=getStat(id);
  return sk.comps.slice().sort((a,b)=>{
    const A=st.components[a]||{possible:0,earned:0};
    const B=st.components[b]||{possible:0,earned:0};
    if((A.possible||0)!==(B.possible||0))return (A.possible||0)-(B.possible||0);
    const ar=A.possible?A.earned/A.possible:0;
    const br=B.possible?B.earned/B.possible:0;
    return ar-br;
  })[0];
}
const BUILD_OBJECTS=["tabletop","cabinet panel","shelf","door panel","workbench","floor section","window frame","storage box","bench","tool rack","drawer front","partition"];
const BUILD_PLACES=["study room","bedroom","workshop","kitchen","garage","classroom","store room","hallway"];
function G(text,answer,hint,context,component,key,visual=""){return numeric(text,answer,hint,context,visual,component,key)}
function C(text,answer,wrong,hint,context,component,key,visual=""){return mc(text,answer,wrong,hint,context,visual,component,key)}
const GENERATORS={
  q1_area(context,comp){
    const obj=pick(BUILD_OBJECTS),l=rand(2,15),w=rand(2,12),a=l*w,unit=pick(["cm","m"]),v=rand(1,4);
    if(comp==="square_units"){
      if(v%2===0){const l2=rand(2,15),w2=rand(2,12),a2=l2*w2,ans=a>a2?"first":a<a2?"second":"same";return C(`Two ${obj}s use square tiles. First: ${l} rows of ${w}. Second: ${l2} rows of ${w2}. Which covers more area?`,ans,["first","second","same"].filter(x=>x!==ans),"Count the square units in each surface.",context,comp,qkey("q1_area","sq-compare",[l,w,l2,w2,obj]));}
      return G(`A ${obj} has ${l} rows of ${w} equal square tiles. How many square tiles cover it?`,a,"Count square units by rows × tiles per row.",context,comp,qkey("q1_area","sq-count",[obj,l,w]));
    }
    if(comp==="formula"){
      if(v%2===0)return G(`A rectangular ${obj} has area ${a} ${unit}² and width ${w} ${unit}. What is its length?`,l,"Use area = length × width and find the missing factor.",context,comp,qkey("q1_area","missing",[obj,a,w,unit]));
      return G(`A ${obj} is ${l} ${unit} long and ${w} ${unit} wide. What is its area?`,a,"Multiply length × width.",context,comp,qkey("q1_area","formula",[obj,l,w,unit]));
    }
    if(comp==="units")return C(`The area of a ${l} ${unit} by ${w} ${unit} ${obj} is ${a}. Which label is correct?`,`${a} ${unit}²`,[`${a} ${unit}`,`${a} ${unit}³`,`${l+w} ${unit}²`],"Area uses square units.",context,comp,qkey("q1_area","units",[obj,l,w,unit]));
    if(v===1){const stock=a+rand(5,40);return G(`The shop has ${stock} one-${unit}² tiles. A ${obj} needs ${l} by ${w} ${unit}. How many tiles remain?`,stock-a,"Find the area needed, then subtract from stock.",context,comp,qkey("q1_area","stock",[obj,stock,l,w,unit]));}
    return G(`A ${pick(BUILD_PLACES)} needs a ${l} ${unit} by ${w} ${unit} surface covered. Each panel covers 1 ${unit}². How many panels are needed?`,a,"Find the surface area.",context,comp,qkey("q1_area","application",[obj,l,w,unit,v]));
  },
  q1_lines(context,comp){
    const obj=pick(BUILD_OBJECTS);
    if(comp==="objects"){const x=pick([["one endpoint and continues one way","ray"],["two endpoints","segment"],["continues both ways","line"],["marks an exact location","point"]]);return C(`On a blueprint, a mark has ${x[0]}. What is it?`,x[1],["point","line","segment","ray"].filter(v=>v!==x[1]),"Use endpoints and direction.",context,comp,qkey("q1_lines","object",[x[1],obj]));}
    if(comp==="equal_segments"){const a=rand(2,30),b=rand(2,30),ans=a===b?"equal":"not equal";return C(`Two cut segments are ${a} cm and ${b} cm. Are they equal?`,ans,["equal","not equal"].filter(v=>v!==ans),"Compare their lengths.",context,comp,qkey("q1_lines","equal",[a,b,obj]));}
    const rel=pick([["parallel","two shelf rails stay the same distance apart"],["perpendicular","a post meets a beam at a square corner"],["intersecting","two braces cross"]]);
    return C(`A ${pick(BUILD_PLACES)} plan shows ${rel[1]}. What relationship is shown?`,rel[0],["parallel","perpendicular","intersecting"].filter(v=>v!==rel[0]),"Look at how the lines meet.",context,comp,qkey("q1_lines","relationship",[rel[0],obj,rand(1,20)]));
  },
  q1_composite(context,comp){
    const rect=pick(["rectangle","square"]),curve=pick(["circle","half-circle","quarter-circle"]),obj=pick(BUILD_OBJECTS),v=rand(1,20);
    if(comp==="identify_parts")return C(`A decorative ${obj} is made from one ${rect} joined to one ${curve}. What kind of figure is the whole design?`,"composite figure",["single line","single point","only a rectangle"],"A composite figure combines familiar shapes.",context,comp,qkey("q1_composite","identify",[rect,curve,obj,v]));
    if(comp==="compose")return C(`Which pair of shapes could build a sign with a rectangular body and a rounded top?`,`rectangle + half-circle`,["point + ray","two parallel lines","triangle only"],"Choose the simple shapes that make the whole.",context,comp,qkey("q1_composite","compose",[rect,curve,obj,v]));
    return C(`An L-shaped ${obj} is made only of right angles. What is a useful way to decompose it?`,`split it into two rectangles`,["split it into two points","treat it as one circle","use only a ray"],"Break the whole into familiar shapes.",context,comp,qkey("q1_composite","decompose",[obj,v,rect]));
  },
  q1_perimeter(context,comp){
    const obj=pick(BUILD_OBJECTS);
    if(comp==="triangle"){const a=rand(2,20),b=rand(2,20),c=rand(2,20);return G(`A triangular brace has sides ${a} cm, ${b} cm, and ${c} cm. What is its perimeter?`,a+b+c,"Add all outside side lengths.",context,comp,qkey("q1_perimeter","triangle",[a,b,c,obj]));}
    if(comp==="square"){const s=rand(2,25);return G(`A square frame has side length ${s} cm. What is its perimeter?`,s*4,"A square has four equal sides.",context,comp,qkey("q1_perimeter","square",[s,obj,rand(1,6)]));}
    const l=rand(3,25),w=rand(2,20),p=2*(l+w);
    if(comp==="rectangle")return G(`A rectangular ${obj} is ${l} cm by ${w} cm. What is its perimeter?`,p,"Add both lengths and both widths.",context,comp,qkey("q1_perimeter","rectangle",[obj,l,w]));
    const stock=p+rand(5,40);return G(`You have ${stock} cm of edge trim. A rectangular ${obj} is ${l} cm by ${w} cm. How much trim remains after going once around it?`,stock-p,"Find the perimeter, then subtract it from stock.",context,comp,qkey("q1_perimeter","application",[obj,l,w,stock]));
  },
  q1_numbers(context,comp){const n=rand(1000,9999),obj=pick(BUILD_OBJECTS);if(comp==="represent"){const th=Math.floor(n/1000),h=Math.floor(n/100)%10,t=Math.floor(n/10)%10,o=n%10;return C(`Which expanded form matches ${n.toLocaleString()}?`,`${th*1000}+${h*100}+${t*10}+${o}`,[`${th*100}+${h*10}+${t}+${o}`,`${th*1000}+${h*10}+${t*100}+${o}`,`${n+100}`],"Break the number into place values.",context,comp,qkey("q1_numbers","expanded",[n,obj]));}return G(`A lumber shipment is labeled ${n.toLocaleString()}. Enter the number without commas.`,n,"Read thousands, hundreds, tens, and ones.",context,comp,qkey("q1_numbers","read",[n,obj]));},
  q1_ordinals(context,comp){const n=rand(4,100),s=n%100>=11&&n%100<=13?"th":n%10===1?"st":n%10===2?"nd":n%10===3?"rd":"th";return C(`Your delivery is number ${n} in the queue. Which ordinal shows its position?`,`${n}${s}`,[`${n+1}th`,`${n-1}th`,`${n}st`],"Ordinal numbers show position.",context,comp,qkey("q1_ordinals","ordinal",[n,pick(BUILD_PLACES)]));},
  q1_place(context,comp){const n=rand(1000,9999),p=pick([["thousands",1000],["hundreds",100],["tens",10],["ones",1]]),d=Math.floor(n/p[1])%10;if(comp==="value")return G(`In stock code ${n}, what is the value of digit ${d} in the ${p[0]} place?`,d*p[1],"Digit value equals digit × place.",context,comp,qkey("q1_place","value",[n,p[1]]));return G(`In stock code ${n}, what digit is in the ${p[0]} place?`,d,"Locate the requested place.",context,comp,qkey("q1_place","place",[n,p[1]]));},
  q1_round(context,comp){const n=rand(1000,9999),base=pick([10,100,1000]);return G(`Round supplier count ${n} to the nearest ${base}.`,Math.round(n/base)*base,"Look one digit to the right of the rounding place.",context,comp,qkey("q1_round","round",[n,base,pick(BUILD_OBJECTS)]));},
  q1_compare(context,comp){const a=rand(1000,9999),b=rand(1000,9999);if(comp==="order"){const c=rand(1000,9999),arr=[a,b,c].sort((x,y)=>x-y);return C(`Order these stock counts least to greatest: ${a}, ${b}, ${c}.`,arr.join(", "),[[...arr].reverse().join(", "),[arr[1],arr[0],arr[2]].join(", "),[arr[0],arr[2],arr[1]].join(", ")],"Compare from the thousands place.",context,comp,qkey("q1_compare","order",[a,b,c]));}const ans=a>b?">":a<b?"<":"=";return C(`Compare stock counts: ${a} __ ${b}.`,ans,["<",">","="].filter(v=>v!==ans),"Compare from the largest place.",context,comp,qkey("q1_compare","compare",[a,b]));},
  q2_mass(context,comp){if(comp==="compare"){const a=rand(100,950),b=rand(100,950),ans=a>b?"first":a<b?"second":"same";return C(`Two hardware boxes weigh ${a} g and ${b} g. Which is heavier?`,ans,["first","second","same"].filter(v=>v!==ans),"Compare equal units.",context,comp,qkey("q2_mass","compare",[a,b,pick(BUILD_OBJECTS)]));}if(comp==="estimate"){const x=pick([["hammer",800,"g"],["nail",5,"g"],["toolbox",4,"kg"],["washer",8,"g"]]);return C(`Which is a sensible estimate for a ${x[0]}?`,`${x[1]} ${x[2]}`,[`${x[1]*10} ${x[2]}`,`${Math.max(1,Math.floor(x[1]/10))} ${x[2]}`,`${x[1]} ${x[2]==="kg"?"mg":"kg"}`],"Use a realistic estimate.",context,comp,qkey("q2_mass","estimate",[x[0],x[1],rand(1,30)]));}const x=pick([["hammer","kg"],["box of nails","g"],["tiny screw","mg"],["wood plank","kg"],["washer","g"]]);return C(`Which unit is sensible for the mass of a ${x[0]}?`,x[1],["g","kg","mg"].filter(v=>v!==x[1]),"Match the unit to the object.",context,comp,qkey("q2_mass","unit",[x[0],rand(1,50)]));},
  q2_capacity(context,comp){if(comp==="compare"){const a=rand(150,950),b=rand(150,950),ans=a>b?"first":a<b?"second":"same";return C(`Two glue bottles hold ${a} mL and ${b} mL. Which holds more?`,ans,["first","second","same"].filter(v=>v!==ans),"Compare equal units.",context,comp,qkey("q2_capacity","compare",[a,b,pick(BUILD_OBJECTS)]));}if(comp==="estimate"){const x=pick([["paint can",4,"L"],["glue bottle",250,"mL"],["water jug",2,"L"],["varnish bottle",500,"mL"]]);return C(`Which is a sensible capacity for a ${x[0]}?`,`${x[1]} ${x[2]}`,[`${x[1]*10} ${x[2]}`,`${Math.max(1,Math.floor(x[1]/10))} ${x[2]}`,`${x[1]} ${x[2]==="L"?"mL":"L"}`],"Use a realistic estimate.",context,comp,qkey("q2_capacity","estimate",[x[0],x[1],rand(1,30)]));}const x=pick([["paint can","L"],["glue bottle","mL"],["water jug","L"],["small varnish bottle","mL"]]);return C(`Which unit is sensible for the capacity of a ${x[0]}?`,x[1],["L","mL"].filter(v=>v!==x[1]),"Match the unit to the container.",context,comp,qkey("q2_capacity","unit",[x[0],rand(1,50)]));},
  q2_time(context,comp){const h=rand(1,11),m=pick([0,5,10,15,20,25,30,35,40,45,50,55]),period=pick(["a.m.","p.m."]);if(comp==="tell_write")return C(`A customer appointment is ${h}:${String(m).padStart(2,"0")} ${period}. Which written time matches?`,`${h}:${String(m).padStart(2,"0")} ${period}`,[`${h}:${String((m+10)%60).padStart(2,"0")} ${period}`,`${h}:00 ${period}`,`${h}:${String(m).padStart(2,"0")} ${period==="a.m."?"p.m.":"a.m."}`],"Read the hour, minutes, and time of day.",context,comp,qkey("q2_time","tell",[h,m,period,pick(BUILD_PLACES)]));if(comp==="am_pm"){const event=period==="a.m."?pick(["morning delivery","breakfast-time repair","early workshop opening"]):pick(["afternoon install","evening pickup","after-lunch inspection"]);return C(`A ${event} is scheduled at ${h}:${String(m).padStart(2,"0")}. Which label is sensible?`,period,[period==="a.m."?"p.m.":"a.m."],"Use a.m. before noon and p.m. after noon.",context,comp,qkey("q2_time","ampm",[event,h,m,period]));}const addH=rand(1,3),addM=pick([0,15,30,45]),endTotal=h*60+m+addH*60+addM,endH=Math.floor(endTotal/60)%12||12,endM=endTotal%60;if(comp==="duration")return G(`A repair lasts ${addH} hour${addH>1?"s":""} ${addM} minutes. How many minutes is that?`,addH*60+addM,"Convert hours to minutes, then add.",context,comp,qkey("q2_time","duration",[h,m,addH,addM]));return C(`A ${pick(BUILD_OBJECTS)} job starts at ${h}:${String(m).padStart(2,"0")}. It lasts ${addH} hour${addH>1?"s":""} ${addM} minutes. What time does it end?`,`${endH}:${String(endM).padStart(2,"0")}`,[`${h}:${String(endM).padStart(2,"0")}`,`${endH}:${String((endM+15)%60).padStart(2,"0")}`,`${Math.max(1,endH-1)}:${String(endM).padStart(2,"0")}`],"Move forward by the elapsed hours and minutes.",context,comp,qkey("q2_time","elapsed",[h,m,addH,addM]));},
  q2_money(context,comp){const p=rand(120,9800);return G(`A hardware receipt totals ${peso(p)}. Enter the peso amount.`,p,"Read the peso value.",context,comp,qkey("q2_money","money",[p,pick(BUILD_OBJECTS)]));},
  q2_add(context,comp){const a=rand(500,4500),b=rand(400,4500);if(a+b>9999)return GENERATORS.q2_add(context,comp);return G(`Wood costs ${peso(a)} and hardware costs ${peso(b)}. What is the total?`,a+b,"Add by place value.",context,comp,qkey("q2_add","add",[a,b,pick(BUILD_OBJECTS)]));},
  q2_addest(context,comp){const a=rand(1100,4700),b=rand(900,3900);return G(`Estimate ${a} + ${b} by rounding each to the nearest hundred.`,Math.round(a/100)*100+Math.round(b/100)*100,"Round both, then add.",context,comp,qkey("q2_addest","estimate",[a,b,pick(BUILD_OBJECTS)]));},
  q2_addprob(context,comp){const a=rand(500,4200),b=rand(400,4200),extra=comp==="money"?rand(50,500):rand(1,50);if(a+b+extra>9999)return GENERATORS.q2_addprob(context,comp);return G(`A ${pick(BUILD_OBJECTS)} costs ${peso(a)}, hardware costs ${peso(b)}, and an extra item costs ${peso(extra)}. What is the total?`,a+b+extra,"Add all required amounts.",context,comp,qkey("q2_addprob","problem",[a,b,extra,pick(BUILD_PLACES)]));},
  q2_sub(context,comp){const a=rand(3000,9999),b=rand(500,a-100);return G(`You stocked ${a} screws and used ${b}. How many remain?`,a-b,"Subtract used stock from starting stock.",context,comp,qkey("q2_sub","subtract",[a,b,pick(BUILD_OBJECTS)]));},
  q2_subest(context,comp){const a=rand(4000,9999),b=rand(500,3500);return G(`Estimate ${a} − ${b} by rounding both to the nearest hundred.`,Math.round(a/100)*100-Math.round(b/100)*100,"Round, then subtract.",context,comp,qkey("q2_subest","estimate",[a,b,pick(BUILD_OBJECTS)]));},
  q2_mixed(context,comp){const s=rand(40,80),a=rand(5,15),b=rand(5,15),c=rand(3,10);return G(`Inventory starts with ${s} boards. Buy ${a}, use ${b}, then receive ${c}. How many now?`,s+a-b+c,"Follow events in order.",context,comp,qkey("q2_mixed","mixed",[s,a,b,c,pick(BUILD_OBJECTS)]));},
  q3_data(context,comp){const v=[rand(2,12),rand(2,12),rand(2,12),rand(2,12)],labels=["Shelves","Doors","Tables","Cabinets"],visual=`<div>${v.map((x,i)=>`<div class="small">${labels[i]}: ${"▮".repeat(x)} ${x}</div>`).join("")}</div>`;if(comp==="experiment")return G(`A workshop survey records ${v.reduce((a,b)=>a+b,0)} jobs across four types. How many observations were collected?`,v.reduce((a,b)=>a+b,0),"Add all recorded frequencies.",context,comp,qkey("q3_data","experiment",v),visual);const mx=Math.max(...v),idx=v.indexOf(mx);return C("Which job type has the greatest frequency?",labels[idx],labels.filter(x=>x!==labels[idx]),"Compare the frequencies.",context,comp,qkey("q3_data","table",v),visual);},
  q3_graph(context,comp){const v=[rand(2,12),rand(2,12),rand(2,12),rand(2,12)],labels=["Shelves","Doors","Tables","Cabinets"],visual=`<div>${v.map((x,i)=>`<div class="small">${labels[i]}: ${"▮".repeat(x)} ${x}</div>`).join("")}</div>`;if(comp==="solve"){const hi=Math.max(...v),lo=Math.min(...v);return G("How many more jobs are in the largest category than the smallest?",hi-lo,"Find largest minus smallest.",context,comp,qkey("q3_graph","difference",v),visual);}const mx=Math.max(...v),idx=v.indexOf(mx);return C("Which job type has the greatest bar?",labels[idx],labels.filter(x=>x!==labels[idx]),"Compare bar heights.",context,comp,qkey("q3_graph","interpret",v),visual);},
  q3_probability(context,comp){const a=rand(2,10),b=rand(1,10);if(comp==="certain_impossible")return C(`A box contains only ${a} wood screws. Picking a brass screw is…`,"impossible",["certain","more likely","equally likely"],"An absent outcome cannot happen.",context,comp,qkey("q3_probability","impossible",[a,pick(BUILD_OBJECTS),rand(1,30)]));const ans=a>b?"wood screw":a<b?"brass screw":"equally likely";return C(`A bin has ${a} wood screws and ${b} brass screws. What is more likely?`,ans,["wood screw","brass screw","equally likely"].filter(x=>x!==ans),"Compare how many of each are present.",context,comp,qkey("q3_probability","likely",[a,b,pick(BUILD_PLACES)]));},
  q3_facts(context,comp){const map={six:6,seven:7,eight:8,nine:9},a=map[comp]||pick([6,7,8,9]),b=rand(2,12),obj=pick(BUILD_OBJECTS);return G(`${b} ${obj}s need ${a} screws each. How many screws?`,a*b,"Use equal groups.",context,comp,qkey("q3_facts","facts",[a,b,obj,context]));},
  q3_props(context,comp){const a=rand(2,9),b=rand(2,9),c=rand(2,5);if(comp==="identity")return G(`${a} × 1 = ?`,a,"Identity keeps the number.",context,comp,qkey("q3_props","identity",[a,pick(BUILD_OBJECTS)]));if(comp==="zero")return G(`${a} × 0 = ?`,0,"Any number times zero is zero.",context,comp,qkey("q3_props","zero",[a,pick(BUILD_OBJECTS)]));if(comp==="commutative")return C(`Which expression has the same product as ${a} × ${b}?`,`${b} × ${a}`,[`${a}+${b}`,`${a}×${b+1}`,`${a}-${b}`],"Factors may switch order.",context,comp,qkey("q3_props","commutative",[a,b,pick(BUILD_OBJECTS)]));if(comp==="associative")return C(`Which expression matches (${a} × ${b}) × ${c}?`,`${a} × (${b} × ${c})`,[`${a+b} × ${c}`,`${a} × (${b}+${c})`,`(${a}+${b}) × ${c}`],"Grouping may change without changing factor order.",context,comp,qkey("q3_props","associative",[a,b,c,pick(BUILD_OBJECTS)]));return C(`Which breaks apart ${a} × ${b+c} correctly?`,`${a}×${b} + ${a}×${c}`,[`${a+b}×${c}`,`${a}×${b} + ${c}`,`${a+b+c}`],"Distribute the factor to both parts.",context,comp,qkey("q3_props","distributive",[a,b,c,pick(BUILD_OBJECTS)]));},
  q3_mult(context,comp){const a=rand(21,399),b=rand(2,9);if(a*b>9999)return GENERATORS.q3_mult(context,comp);return G(`${b} bundles contain ${a} fasteners each. How many fasteners altogether?`,a*b,"Multiply the groups.",context,comp,qkey("q3_mult","multiply",[a,b,pick(BUILD_OBJECTS)]));},
  q3_estprod(context,comp){const a=rand(21,189),b=rand(11,49),ra=Math.round(a/10)*10,rb=Math.round(b/10)*10;return G(`Estimate ${a} × ${b} by rounding both factors to the nearest 10.`,ra*rb,"Round, then multiply.",context,comp,qkey("q3_estprod","estimate",[a,b,pick(BUILD_OBJECTS)]));},
  q3_multprob(context,comp){const groups=rand(2,9),each=rand(12,120),extra=comp==="money"?rand(20,200):rand(1,20),base=groups*each;return G(`${groups} rooms need ${each} fasteners each, plus ${extra} extra fasteners. How many are needed altogether?`,base+extra,"Multiply the equal groups, then add the extra amount.",context,comp,qkey("q3_multprob","two-step",[groups,each,extra,pick(BUILD_PLACES)]));},
  q3_patterns(context,comp){const start=rand(2,30),inc=rand(2,9),dir=pick([1,-1]),safe=dir===1?start:start+inc*6,seq=[safe,safe+dir*inc,safe+dir*inc*2,safe+dir*inc*3];if(comp==="explain")return C(`Pattern: ${seq.join(", ")}. What is the rule?`,`${dir===1?"add":"subtract"} ${inc}`,[`${dir===1?"subtract":"add"} ${inc}`,`${dir===1?"add":"subtract"} ${inc+1}`,"double each term"],"Find the same change each step.",context,comp,qkey("q3_patterns","rule",[safe,inc,dir,pick(BUILD_OBJECTS)]));if(comp==="generate")return G(`Start at ${safe}. ${dir===1?"Add":"Subtract"} ${inc} three times. What is the third new term?`,safe+dir*inc*3,"Apply the same rule repeatedly.",context,comp,qkey("q3_patterns","generate",[safe,inc,dir,pick(BUILD_OBJECTS)]));return G(`Cut lengths follow ${seq.join(", ")}, __. What comes next?`,safe+dir*inc*4,"Find the change from term to term.",context,comp,qkey("q3_patterns","next",[safe,inc,dir,pick(BUILD_OBJECTS)]));},
  q4_divconcept(context,comp){const d=rand(2,9),q=rand(2,30),n=d*q;if(comp==="inverse")return C(`${d} × ${q} = ${n}. Which related division fact is correct?`,`${n} ÷ ${d} = ${q}`,[`${n} ÷ ${q} = ${d+1}`,`${d+q} ÷ ${d} = ${q}`,`${n} ÷ ${d+1} = ${q}`],"Division reverses multiplication.",context,comp,qkey("q4_divconcept","inverse",[d,q,pick(BUILD_OBJECTS)]));if(comp==="missing")return G(`${n} screws are split into ${d} equal groups. How many screws are in each group?`,q,"Use the related multiplication fact.",context,comp,qkey("q4_divconcept","missing",[n,d,pick(BUILD_OBJECTS)]));return G(`${n} screws are packed in groups of ${d}. How many complete groups?`,q,"Use the related multiplication fact.",context,comp,qkey("q4_divconcept","groups",[n,d,pick(BUILD_OBJECTS)]));},
  q4_div(context,comp){const d=rand(2,9),q=rand(2,30),r=comp==="remainder"?rand(1,d-1):0,n=d*q+r;if(comp==="remainder")return C(`${n} screws are packed in groups of ${d}. What is the result?`,`${q} remainder ${r}`,[`${q+1} remainder 0`,`${q} remainder ${Math.max(0,r-1)}`,`${q-1} remainder ${r}`],"Make complete groups, then count what is left.",context,comp,qkey("q4_div","remainder",[n,d,pick(BUILD_OBJECTS)]));return G(`${n} screws are packed in groups of ${d}. How many complete groups?`,Math.floor(n/d),"Use the related multiplication fact.",context,comp,qkey("q4_div","division",[n,d,pick(BUILD_OBJECTS),context]));},
  q4_estquot(context,comp){const d=pick([20,30,40,50]),q=rand(3,9),friendly=d*q,n=friendly+pick([-9,-7,-4,4,7,9]);return G(`Estimate ${n} ÷ ${d} using nearby friendly dividend ${friendly}.`,q,"Use the nearby dividend that divides evenly.",context,comp,qkey("q4_estquot","estimate",[n,d,friendly,pick(BUILD_OBJECTS)]));},
  q4_divprob(context,comp){const d=pick([6,7,8,9]),q=rand(10,40),n=d*q;return G(`${peso(n)} of materials is shared equally across ${d} rooms. Cost per room?`,q,"Divide total cost by rooms.",context,comp,qkey("q4_divprob","money",[n,d,pick(BUILD_PLACES)]));},
  q4_fracrep(context,comp){const den=pick([2,3,4,5,6,8]),num=comp==="equal_one"?den:rand(den+1,den*2+2);return C(`Which fraction represents ${num} equal parts when one whole has ${den} parts?`,`${num}/${den}`,[`${den}/${num}`,`${num-1}/${den}`,`${num}/${den+1}`],"Numerator counts parts; denominator gives parts per whole.",context,comp,qkey("q4_fracrep","represent",[num,den,pick(BUILD_OBJECTS)]));},
  q4_fracops(context,comp){const den=pick([3,4,5,6,8]),a=rand(1,den-1),b=rand(1,den-1);if(comp==="subtraction"){const hi=Math.max(a,b),lo=Math.min(a,b);return C(`${hi}/${den} m minus ${lo}/${den} m equals?`,`${hi-lo}/${den}`,[`${hi+lo}/${den}`,`${hi-lo}/${den*2}`,`${Math.max(0,hi-lo-1)}/${den}`],"Keep the denominator and subtract numerators.",context,comp,qkey("q4_fracops","subtract",[hi,lo,den,pick(BUILD_OBJECTS)]));}if(comp==="models")return C(`A board is divided into ${den} equal parts and ${a} are marked. Which fraction is marked?`,`${a}/${den}`,[`${den}/${a}`,`${a+1}/${den}`,`${a}/${den+1}`],"Count marked parts over total equal parts.",context,comp,qkey("q4_fracops","model",[a,den,pick(BUILD_OBJECTS)]));return C(`${a}/${den} m plus ${b}/${den} m equals?`,`${a+b}/${den}`,[`${a+b}/${den*2}`,`${Math.abs(a-b)}/${den}`,`${a+b}/${den+1}`],"Keep the denominator and add numerators.",context,comp,qkey("q4_fracops","add",[a,b,den,pick(BUILD_OBJECTS)]));},
  q4_translation(context,comp){const h=rand(1,6),v=rand(1,6),hd=pick(["right","left"]),vd=pick(["up","down"]);return C(`A template slides ${h} squares ${hd} and ${v} squares ${vd}. Which describes the movement?`,`${hd} ${h}, ${vd} ${v}`,[`${hd==="right"?"left":"right"} ${h}, ${vd} ${v}`,`${hd} ${v}, ${vd} ${h}`,`${hd} ${h}, ${vd==="up"?"down":"up"} ${v}`],"Track horizontal and vertical movement separately.",context,comp,qkey("q4_translation","translate",[h,v,hd,vd,pick(BUILD_OBJECTS)]));},
  q4_symmetry(context,comp){const fam=pick([["centered rectangular door","vertical"],["square tile","vertical and horizontal"],["isosceles roof front","vertical"],["rectangular tabletop","vertical and horizontal"]]);return C(`Which symmetry description fits a ${fam[0]}?`,fam[1],["none","horizontal only","diagonal only","vertical only"].filter(x=>x!==fam[1]),"Imagine folding along possible mirror lines.",context,comp,qkey("q4_symmetry","symmetry",[fam[0],fam[1],pick(BUILD_PLACES),rand(1,30)]));}
};
function genQuestion(skillId,context){
  const comp=weakestComponent(skillId),generator=GENERATORS[skillId];
  if(!generator)return G("Enter 0.",0,"Fallback question.",context,comp,qkey(skillId,"fallback",[skillId,comp]));
  return unseen(skillId,()=>generator(context,comp));
}
